### ISSUE TITLE
Bootstrap 3 clobbers console

### ISSUE THREAD

**Issue by jasonl99** [rails/web-console#57]
I have an on-page console, and bootstrap has some pretty liberal css that really messes up the display

![console](https://cloud.githubusercontent.com/assets/1554969/4600178/e18d01fc-50cf-11e4-8e61-118b9b09a9b6.png)

 (ignore the thumbs above the console...I just captured too much)

I added this to application.css.scss to override bootstrap's css:

``` scss
div#console, [class^='console-'] {
  padding: 0;
  background: none repeat scroll 0% 0% #333;
  margin: 0;
  font-size: 11px;
  color: #1ad027;
  overflow: auto;
  pre {
    border: 0;
    white-space: pre-wrap;
  }
}
```

and I ended up with this

![console2](https://cloud.githubusercontent.com/assets/1554969/4600212/74fd9168-50d0-11e4-89d4-28902ebc09e6.png)

I'm not sure what the right approach is here, but I thought I'd throw this out there.
